words = ('ant baboon badger bat bear beaver camel cat clam cobra cougar '
         'coyote crow deer dog donkey duck eagle ferret fox frog goat '
         'goose hawk lion lizard llama mole monkey moose mouse mule newt '
         'otter owl panda parrot pigeon python rabbit ram rat raven '
         'rhino salmon seal shark sheep skunk sloth snake spider '
         'stork swan tiger toad trout turkey turtle weasel whale wolf '
         'wombat zebra '
         'able about account acid across act addition adjustment '
         'air all almost among amount amusement and angle angry animal '
         'arch argument arm army art as at attack attempt attention '
         'baby back bad bag balance ball band basebasin basket bath be '
         'belief bell bent berry between bird birth bit bite bitter black '
         'boiling bone book boot bottle box boy brain brake branch brass '
         'brother brown brush bucket building bulb burn burst business '
         'cake camera canva card care carriage cart cat cause certain '
         'chest chief chin church circle clean clear clock cloth cloud '
         'committee common company comparison competition complete '
         'copper copy cord cork cotton cough country cover cow crack '
         'curve cushion damage danger dark daughter day  dead dear '
         'design desire destruction detail development different '
         'disgust distance distribution division do dog door doubt '
         'ear early earth east edge education effect egg elastic '
         'every example exchange existence expansion experience '
         'father fear feather feeble feeling female fertile fiction '
         'flame flat flight floor flower fly fold food foolish foot '
         'friend from front fruit full future garden general get girl '
         'grass great green grey grip group growth  guide gun hair hammer '
         'have he head healthy hear hearing heart heat help high history '
         'how humour I ice idea if ill important impulse in increase '
         'iron island jelly jewel join journey judge jump keep kettle key '
         'last late laugh law  lead leaf learning leather left leg let '
         'linen lip liquid list little living lock long look loose loss '
         'market married  mass match material may meal measure meat '
         'mine minute mist mixed money monkey month moon morning mother '
         'name narrow nation natural near necessary neck need needle '
         'note now number nut observation of off offer office oil old '
         'organization ornament other out oven over owner page pain paint '
         'pen pencil person physical picture pig pin pipe place plane plant '
         'poison polish political poor porter position possible pot potato '
         'process produce profit property prose protest public pull pump '
         'quite rail rain range rat rate ray reaction reading ready reason '
         'representative request respect responsible rest reward rhythm rice '
         'rough round rub rule run sad safe sail salt same sand say scale '
         'secret secretary see seed seem selection self send sense separate '
         'shelf ship shirt shock shoe short shut side sign silk silver simple '
         'slow small smash smell smile smoke smooth snake sneeze snow so soap '
         'sound soup south space spade special sponge spoon spring square '
         'steel stem step stick sticky stiff still stitch stocking stomach '
         'stretch strong structure substance such sudden sugar suggestion '
         'table tail take talk tall taste tax teaching tendency test than '
         'thought thread throat through through thumb thunder ticket tight '
         'tooth top touch town trade train transport tray tree trick '
         'under unit up use value verse very vessel view violent voice '
         'way weather week weight well west wet wheel when where while whip '
         'window wine wing winter wire wise with woman wood wool word work ').split()